SLOT_DATABASE.push(
  {
    name: "Crypto Crown 40",
    provider: "Avatar UX",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/avatarux/crypto-crown-40/",
  },
  {
    name: "Carioca Vibes",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/carioca-vibes/",
  },
  {
    name: "3 Power Dragons",
    provider: "Avatar UX",
    maxWin: "15000x",
    demo: "https://clashofslots.com/slots/avatarux/3-power-dragons/",
  },
  {
    name: "Shippy D. POP",
    provider: "Avatar UX",
    maxWin: "50000x",
    demo: "https://clashofslots.com/slots/avatarux/shippy-d-pop/",
  },
  {
    name: "Crypto Bro",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/crypto-bro/",
  },
  {
    name: "Fruitillionaire",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/fruitillionaire/",
  },
  {
    name: "Sphinx Treasure",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/sphinx-treasure/",
  },
  {
    name: "Big Catch Xmas",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/big-catch-xmas/",
  },
  {
    name: "3 Power Genies",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/3-power-genies/",
  },
  {
    name: "MonkeyPop 2",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/monkeypop-2/",
  },
  {
    name: "Diamond Dez",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/diamond-dez/",
  },
  {
    name: "Midnight Hunt",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/midnight-hunt/",
  },
  {
    name: "Spinfection",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/spinfection/",
  },
  {
    name: "Coyote Gold",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/coyote-gold/",
  },
  {
    name: "AstroPop",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/astropop/",
  },
  {
    name: "CherryPop Burst",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://respinix.com/demo/cherrypop-burst/",
  },
  {
    name: "Spinxiety",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/spinxiety/",
  },
  {
    name: "Electric Rush",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/electric-rush/",
  },
  {
    name: "The Vault Chase",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/the-vault-chase/",
  },
  {
    name: "Reel Warriors",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/reel-warriors/",
  },
  {
    name: "Cosmic Jokers",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/cosmic-jokers/",
  },
  {
    name: "Rebel Paws",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/rebel-paws/",
  },
  {
    name: "Captain More'gain",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/captain-moregain/",
  },
  {
    name: "Duck Hunt 500",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/duck-hunt-500/",
  },
  {
    name: "Electro Cubes",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/electro-cubes/",
  },
  {
    name: "Vegas Fortune",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/vegas-fortune/",
  },
  {
    name: "PiggyPop Grand Affair",
    provider: "Avatar UX",
    maxWin: "5000x",
    demo: "https://www.demoslotsfun.com/slots/piggypop-grand-affair-demo-slot",
  },
  {
    name: "Canyon Riches",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/canyon-riches/",
  },
  {
    name: "Silicon Spinners",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/silicon-spinners/",
  },
  {
    name: "Big Catch Craze",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/big-catch-craze/",
  },
  {
    name: "Jungle Pop",
    provider: "Avatar UX",
    maxWin: "50000x",
    demo: "https://clashofslots.com/slots/avatarux/junglepop/",
  },
  {
    name: "Pixel Paws",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/pixel-paws/",
  },
  {
    name: "Imperial Coins",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://great.com/slots/imperial-coins/",
  },
  {
    name: "Gods Gone Wld",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/gods-gone-wild/",
  },
  {
    name: "Animals Strike",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/animals-strike/",
  },
  {
    name: "Tik Talkers",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/tik-talkers/",
  },
  {
    name: "XmasPop Delight",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/xmaspop-delight/",
  },
  {
    name: "TikiPop Spooky Temples",
    provider: "Avatar UX",
    maxWin: "32000x",
    demo: "https://clashofslots.com/slots/avatarux/tikipop-spooky-temples/",
  },
  {
    name: "Juicy Pop",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/juicypop/",
  },
  {
    name: "Sweet Gummy",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/sweet-gummy/",
  },
  {
    name: "Beastly Burglars",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/beastly-burglars/",
  },
  {
    name: "Depths of Fortune",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/depths-of-fortune/",
  },
  {
    name: "Arcana Pop",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/arcanapop/",
  },
  {
    name: "Floridaman",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/floridaman/",
  },
  {
    name: "PopNoir",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/popnoir/",
  },
  {
    name: "Nugget",
    provider: "Avatar UX",
    maxWin: "25000x",
    demo: "https://clashofslots.com/slots/avatarux/nugget/",
  },
  {
    name: "Worms of Valor",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/worms-of-valor/",
  },
  {
    name: "Looney Pop",
    provider: "Avatar UX",
    maxWin: "50000x",
    demo: "https://clashofslots.com/slots/avatarux/looneypop/",
  },
  {
    name: "Pop O'Gold",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/pop-o-gold-popwins/",
  },
  {
    name: "Tiki Pop",
    provider: "Avatar UX",
    maxWin: "32015x",
    demo: "https://clashofslots.com/slots/avatarux/tikipop/",
  },
  {
    name: "Wild Pops",
    provider: "Avatar UX",
    maxWin: "17707x",
    demo: "https://clashofslots.com/slots/avatarux/wild-pops/",
  },
  {
    name: "Witchy POPpins",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/witchypoppins/",
  },
  {
    name: "Zombie aPOPalypse",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/zombie-apopalypse/",
  },
  {
    name: "80sPOP",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/80spop/",
  },
  {
    name: "Critter Pop",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/critterpop/",
  },
  {
    name: "HelioPOPolis",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/heliopopolis/",
  },
  {
    name: "ReefPOP",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/reefpop/",
  },
  {
    name: "Hippo Pop",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/hippopop/",
  },
  {
    name: "JinglePOP",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/jinglepop/",
  },
  {
    name: "Kitty POPpins",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/kitty-poppins/",
  },
  {
    name: "Papaya Pop",
    provider: "Avatar UX",
    maxWin: "10542x",
    demo: "https://clashofslots.com/slots/avatarux/papayapop/",
  },
  {
    name: "Bounty Pop",
    provider: "Avatar UX",
    maxWin: "55000x",
    demo: "https://clashofslots.com/slots/avatarux/bountypop/",
  },
  {
    name: "GemPops",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/gempops/",
  },
  {
    name: "Piggy Pop",
    provider: "Avatar UX",
    maxWin: "10690x",
    demo: "https://clashofslots.com/slots/avatarux/piggypop/",
  },
  {
    name: "PixiePop",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/pixiepop/",
  },
  {
    name: "Cherry Pop Deluxe",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/cherrypop-deluxe/",
  },
  {
    name: "Monkey Pop",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/monkeypop/",
  },
  {
    name: "Raging Pop",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/avatarux/ragingpop/",
  },
  {
    name: "Donkey and The GOATS",
    provider: "Avatar UX",
    maxWin: "20000x",
    demo: "https://slotslaunch.com/avatarux/donkey-and-the-goats",
  },
  {
    name: "HipHopPop",
    provider: "Avatar UX",
    maxWin: "50000x",
    demo: "https://clashofslots.com/slots/avatarux/hiphoppop/",
  },
  {
    name: "Lolli Pop",
    provider: "Avatar UX",
    maxWin: "13000x",
    demo: "https://clashofslots.com/slots/avatarux/lollipop/",
  },
  {
    name: "Kokeshi Pop",
    provider: "Avatar UX",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/avatarux/kokeshipop/",
  },
  {
    name: "Cherry Pop",
    provider: "Avatar UX",
    maxWin: "56386x",
    demo: "https://clashofslots.com/slots/avatarux/cherrypop/",
  },
  {
    name: "Pop Rocks",
    provider: "Avatar UX",
    maxWin: "72188x",
    demo: "https://clashofslots.com/slots/avatarux/pop-rocks/",
  },
);
