SLOT_DATABASE.push(
  {
    name: "Big Bass Raceday Repeat",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-raceday-repeat/",
  },
  {
    name: "Wild Skullz",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-skullz/",
  },
  {
    name: "Haunted Crypt",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/haunted-crypt/",
  },
  {
    name: "Rolling in Treasures",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/rolling-in-treasures/",
  },
  {
    name: "Mummy's Jewels 100",
    provider: "Pragmatic Play",
    maxWin: "30000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mummys-jewels-100/",
  },
  {
    name: "Treasures of Osiris",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/Treasures of Osiris/",
  },
  {
    name: "Emerald King - Wheel of Wealth",
    provider: "Pragmatic Play",
    maxWin: "3000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/emerald-king-wheel-of-wealth/",
  },
  {
    name: "Knights vs Barbarians",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/knights-vs-barbarians/",
  },
  {
    name: "Fire Stampede Ultimate",
    provider: "Pragmatic Play",
    maxWin: "12500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fire-stampede-ultimate/",
  },
  {
    name: "3 Magic Eggs",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/3-magic-eggs/",
  },
  {
    name: "Cyberheist City",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/cyberheist-city/",
  },
  {
    name: "Super Tiki Strike",
    provider: "Pragmatic Play",
    maxWin: "50000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/super-tiki-strike/",
  },
  {
    name: "Dragon Tiger Fortunes",
    provider: "Pragmatic Play",
    maxWin: "8200x",
    demo: "https://clashofslots.com/slots/pragmatic-play/dragon-tiger-fortunes/",
  },
  {
    name: "Floating Dragon Wild Horses",
    provider: "Pragmatic Play",
    maxWin: "500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/floating-dragon-wild-horses/",
  },
  {
    name: "Zeus vs Hades - Gods of War 250",
    provider: "Pragmatic Play",
    maxWin: "25000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/zeus-vs-hades-gods-of-war-250/",
  },
  {
    name: "Sugar Rush Super Scatter",
    provider: "Pragmatic Play",
    maxWin: "50000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sugar-rush-super-scatter/",
  },
  {
    name: "Hot Tuna",
    provider: "Pragmatic Play",
    maxWin: "2500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/hot-tuna/",
  },
  {
    name: "Wheel of Happines",
    provider: "Pragmatic Play",
    maxWin: "4000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wheel-of-happiness/",
  },
  {
    name: "Joker's Jewels Hold & Spin",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/jokers-jewels-hold-spin/",
  },
  {
    name: "Fortune of Olympus",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fortune-of-olympus/",
  },
  {
    name: "Anaconda Gold",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/anaconda-gold/",
  },
  {
    name: "Hammerstorm",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/hammerstorm/",
  },
  {
    name: "Big Bass Splash 1000",
    provider: "Pragmatic Play",
    maxWin: "25000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-splash-1000/",
  },
  {
    name: "Bloody Dawn",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/bloody-dawn/",
  },
  {
    name: "Sweet Craze",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sweet-craze/",
  },
  {
    name: "Zeus vs Typhon",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/zeus-vs-typhon/",
  },
  {
    name: "Santa's Slay",
    provider: "Pragmatic Play",
    maxWin: "2000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/santas-slay/",
  },
  {
    name: "Super Gummy Strike",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/super-gummy-strike/",
  },
  {
    name: "Wisdom of Athena 1000 Xmas",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wisdom-of-athena-1000-xmas/",
  },
  {
    name: "Duel of Night & Day",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/duel-of-night-day/",
  },
  {
    name: "Big Bass Christams - Frozen Lake",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-christmas-frozen-lake/",
  },
  {
    name: "Wild Wild Riches Returns",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-wild-riches-returns/",
  },
  {
    name: "Oracle of Gold",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/oracle-of-gold/",
  },
  {
    name: "Starlight Princess Super Scatter",
    provider: "Pragmatic Play",
    maxWin: "50000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/starlight-princess-super-scatter/",
  },
  {
    name: "Pandemic Rising",
    provider: "Pragmatic Play",
    maxWin: "14000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/pandemic-rising/",
  },
  {
    name: "Frightening Frankie",
    provider: "Pragmatic Play",
    maxWin: "2800x",
    demo: "https://clashofslots.com/slots/pragmatic-play/frightening-frankie/",
  },
  {
    name: "Lava Balls",
    provider: "Pragmatic Play",
    maxWin: "4800x",
    demo: "https://clashofslots.com/slots/pragmatic-play/lava-balls/",
  },
  {
    name: "Chests of Cai Shen 2",
    provider: "Pragmatic Play",
    maxWin: "16000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/chests-of-cai-shen-2/",
  },
  {
    name: "Big Bass Halloween 3",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-halloween-3/",
  },
  {
    name: "Mermaid's Treasure Trove",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mermaids-treasure-trove/",
  },
  {
    name: "Hundreds and Thousands",
    provider: "Pragmatic Play",
    maxWin: "2000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/hundreds-and-thousands/",
  },
  {
    name: "Bigger Barn House Bonanza",
    provider: "Pragmatic Play",
    maxWin: "25000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/bigger-barn-house-bonanza/",
  },
  {
    name: "Bounty Hunter",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/bounty-hunter/",
  },
  {
    name: "Sweet Rush Bonanza",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sweet-rush-bonanza/",
  },
  {
    name: "Bee Keeper",
    provider: "Pragmatic Play",
    maxWin: "2100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/bee-keeper/",
  },
  {
    name: "Genie's Gem Bonanza",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/genies-gem-bonanza/",
  },
  {
    name: "Lobster House",
    provider: "Pragmatic Play",
    maxWin: "4000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/lobster-house/",
  },
  {
    name: "Captain Kraken Megaways",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/captain-kraken-megaways/",
  },
  {
    name: "Jackpot Blaze",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/jackpot-blaze/",
  },
  {
    name: "Fire Stampede 2",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fire-stampede-2/",
  },
  {
    name: "Spellmaster",
    provider: "Pragmatic Play",
    maxWin: "40000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/spellmaster/",
  },
  {
    name: "Ice Mints",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/ice-mints/",
  },
  {
    name: "Big Bass Reel Repeat",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play//big-bass-reel-repeat",
  },
  {
    name: "Argonauts",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/argonauts/",
  },
  {
    name: "Sweet Bonanza Super Scatter",
    provider: "Pragmatic Play",
    maxWin: "50000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sweet-bonanza-super-scatter/",
  },
  {
    name: "Wolf Gold 4 Pack",
    provider: "Pragmatic Play",
    maxWin: "5100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wolf-gold-4-pack/",
  },
  {
    name: "Gem Trio",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gem-trio/",
  },
  {
    name: "Zombie School Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/zombie-school-megaways/",
  },
  {
    name: "You Can Piggy Bank On It",
    provider: "Pragmatic Play",
    maxWin: "2100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/you-can-piggy-bank-on-it/",
  },
  {
    name: "Chilli Heat Spicy Spins",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/chilli-heat-spicy-spins/",
  },
  {
    name: "Alien Invaders",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/alien-invaders/",
  },
  {
    name: "Club Tropicana - Happy Hour",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/club-tropicana-happy-hour/",
  },
  {
    name: "Waves of Poseidon",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/waves-of-poseidon/",
  },
  {
    name: "Gem Fire Fortune",
    provider: "Pragmatic Play",
    maxWin: "15000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gem-fire-fortune/",
  },
  {
    name: "Finger Lick'n Free Spins",
    provider: "Pragmatic Play",
    maxWin: "6000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/finger-lickn-free-spins/",
  },
  {
    name: "Gold Party 2 - After Hours",
    provider: "Pragmatic Play",
    maxWin: "10312x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gold-party-2-after-hours/",
  },
  {
    name: "Temple Guardians",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/temple-guardians/",
  },
  {
    name: "Big Bass Boxing Bonus Round",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-boxing-bonus-round/",
  },
  {
    name: "Mummy's Jewels",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mummys-jewels/",
  },
  {
    name: "Wild West Gold Blazing Bounty",
    provider: "Pragmatic Play",
    maxWin: "7500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-west-gold-blazing-bounty/",
  },
  {
    name: "Eye of Spartacus",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/eye-of-spartacus/",
  },
  {
    name: "Majestic Express Gold Run",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/majestic-express-gold-run/",
  },
  {
    name: "Gates of Hades",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gates-of-hades/",
  },
  {
    name: "Mahjong Wins Super Scatter",
    provider: "Pragmatic Play",
    maxWin: "100000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mahjong-wins-super-scatter/",
  },
  {
    name: "Jumbo Safari",
    provider: "Pragmatic Play",
    maxWin: "3000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/jumbo-safari/",
  },
  {
    name: "Sleeping Dragon",
    provider: "Pragmatic Play",
    maxWin: "15000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sleeping-dragon/",
  },
  {
    name: "Fiesta Fortune",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fiesta-fortune/",
  },
  {
    name: "Witch Heart Megaways",
    provider: "Pragmatic Play",
    maxWin: "9000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/witch-heart-megaways/",
  },
  {
    name: "Resurrecting Riches",
    provider: "Pragmatic Play",
    maxWin: "4000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/resurrecting-riches/",
  },
  {
    name: "Big Bass Bonanza 1000",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-bonanza-1000/",
  },
  {
    name: "5 Lions Reborn",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/5-lions-reborn/",
  },
  {
    name: "Gates of Olympus Super Scatter",
    provider: "Pragmatic Play",
    maxWin: "50000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gates-of-olympus-super-scatter/",
  },
  {
    name: "Ride the Lightning",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/ride-the-lightning/",
  },
  {
    name: "Bandit Megaways",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/bandit-megaways/",
  },
  {
    name: "Fruit Party Dice",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fruit-party-dice/",
  },
  {
    name: "Book of Monsters",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/book-of-monsters/",
  },
  {
    name: "Blitz Super Wheel",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/blits-super-wheel/",
  },
  {
    name: "The Dog House - Royal Hunt",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-dong-house-royal-hunt/",
  },
  {
    name: "Big Bass Dice",
    provider: "Pragmatic Play",
    maxWin: "2100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-dice/",
  },
  {
    name: "Volcano Goddess",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/volcano-goddess/",
  },
  {
    name: "Triple Pot Gold",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/triple-pot-gold/",
  },
  {
    name: "Wild Wild Joker",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-wild-joker/",
  },
  {
    name: "Lucky's Wild Pub",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/luckys-wild-pub/",
  },
  {
    name: "Raging Waterfall Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play//raging-waterfall-megaways",
  },
  {
    name: "Sweet Bonanza Dice",
    provider: "Pragmatic Play",
    maxWin: "25000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sweet-bonanza-dice/",
  },
  {
    name: "Gates of Olympus 1000 Dice",
    provider: "Pragmatic Play",
    maxWin: "15000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gates-of-olympus-1000-dice/",
  },
  {
    name: "Big Bass Return to the Races",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-return-to-the-races/",
  },
  {
    name: "Peppe's Pepperoni Pizza Plaza",
    provider: "Pragmatic Play",
    maxWin: "6000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/peppes-pepperoni-pizza-plaza/",
  },
  {
    name: "5 Lions Megaways 2",
    provider: "Pragmatic Play",
    maxWin: "8000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/5-lions-megaways-2/",
  },
  {
    name: "Greedy Fortune Pig",
    provider: "Pragmatic Play",
    maxWin: "8888x",
    demo: "https://clashofslots.com/slots/pragmatic-play/greedy-fortune-pig/",
  },
  {
    name: "Savannah Legend",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/savannah-legend/",
  },
  {
    name: "John Hunter and Galileo's Secrets",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/john-hunter-and-galileos-secret/",
  },
  {
    name: "Bigger Bass Splash",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/bigger-bass-splash/",
  },
  {
    name: "Ancient Island Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/ancient-island-megaways/",
  },
  {
    name: "Escape the Pyramid - Fire & Ice",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/escape-the-pyramid-fire-ice/",
  },
  {
    name: "Wild Wildebeest Wins",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-wildebeest-wins/",
  },
  {
    name: "Wild Wild Pearls",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-wild-pearls/",
  },
  {
    name: "Brick House Bonanza",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/brick-house-bonanza/",
  },
  {
    name: "Irish Crown",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/irish-crown/",
  },
  {
    name: "Floating Dragon - Year of the Snake",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/floating-dragon-year-of-the-snake/",
  },
  {
    name: "Fonzo's Feline Fortunes",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fonzos-feline-fortunes/",
  },
  {
    name: "Aztec Smash",
    provider: "Pragmatic Play",
    maxWin: "9000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/Aztec Smash/",
  },
  {
    name: "Big Bass Bonanza 3 Reeler",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-bonanza-3-reeler/",
  },
  {
    name: "Mining Rush",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mining-rush/",
  },
  {
    name: "Money Stacks Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/money-stacks-megaways/",
  },
  {
    name: "Dragon King Hot Pots",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/dragon-king-hot-pots/",
  },
  {
    name: "Tiny Toads",
    provider: "Pragmatic Play",
    maxWin: "4000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/tiny-toads/",
  },
  {
    name: "Santa's Xmas Rush",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/santas-xmas-rush/",
  },
  {
    name: "Penguins Christams Party Time",
    provider: "Pragmatic Play",
    maxWin: "2000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/penguins-christmas-party-time/",
  },
  {
    name: "Might of Freya Megaways",
    provider: "Pragmatic Play",
    maxWin: "8000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/might-of-freya-megaways/",
  },
  {
    name: "Big Bass Xmas Xtreme",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-xmas-xtreme/",
  },
  {
    name: "Gates of Olympus Xmas 1000",
    provider: "Pragmatic Play",
    maxWin: "15000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gates-of-olympus-xmas-1000/",
  },
  {
    name: "Eternal Empress - Freeze Time",
    provider: "Pragmatic Play",
    maxWin: "4888x",
    demo: "https://clashofslots.com/slots/pragmatic-play/eternal-empress-freeze-time/",
  },
  {
    name: "Himalayan Wild",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/himalayan-wild/",
  },
  {
    name: "Wolf Golf Ultimate",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wolf-gold-ultimate/",
  },
  {
    name: "Moleionaire",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/moleionaire/",
  },
  {
    name: "Candy Corner",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/candy-corner/",
  },
  {
    name: "Fangtastic Freespins",
    provider: "Pragmatic Play",
    maxWin: "2100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fangtastic-freespins/",
  },
  {
    name: "7 Clovers of Fortune",
    provider: "Pragmatic Play",
    maxWin: "4454x",
    demo: "https://clashofslots.com/slots/pragmatic-play/7-clovers-of-fortune/",
  },
  {
    name: "Big Bass Halloween 2",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-halloween-2/",
  },
  {
    name: "Vampy Party",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/vampy-party/",
  },
  {
    name: "Release the Kraken Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/release-the-kraken-megaways/",
  },
  {
    name: "Chests of Cai Shen",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/chests-of-cai-shen/",
  },
  {
    name: "Fortune Hit'n Roll",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fortune-hitn-roll/",
  },
  {
    name: "Wisdom of Athena 1000",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wisdom-of-athena-1000/",
  },
  {
    name: "Badge Blitz",
    provider: "Pragmatic Play",
    maxWin: "3000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/badge-blitz/",
  },
  {
    name: "The Dog House - Muttley Crew",
    provider: "Pragmatic Play",
    maxWin: "7500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-dog-house-muttley-crew/",
  },
  {
    name: "Oodles of Noodles",
    provider: "Pragmatic Play",
    maxWin: "5100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/oodles-of-noodles/",
  },
  {
    name: "Congo Cash XL",
    provider: "Pragmatic Play",
    maxWin: "4400x",
    demo: "https://clashofslots.com/slots/pragmatic-play/congo-cash-xl/",
  },
  {
    name: "Big Bass Vegas Double Down Deluxe",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-vegas-double-down-deluxe/",
  },
  {
    name: "Mystery Mice",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mystery-mice/",
  },
  {
    name: "Mustang Gold Megaways",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mustang-gold-megaways/",
  },
  {
    name: "Angel vs Sinner",
    provider: "Pragmatic Play",
    maxWin: "15000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/angel-vs-sinner/",
  },
  {
    name: "Gem Elevator",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gem-elevator/",
  },
  {
    name: "Aztec Treasure Hunt",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/aztec-treasure-hunt/",
  },
  {
    name: "Forging Wilds",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/forging-wilds/",
  },
  {
    name: "Hot to Burn 7 Deadly Free Spins",
    provider: "Pragmatic Play",
    maxWin: "4000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/hot-to-burn-7-deadly-free-spins/",
  },
  {
    name: "Yeti Quest",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/yeti-quest/",
  },
  {
    name: "Dragon Gold 88",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/dragon-gold-88/",
  },
  {
    name: "Running Sushi",
    provider: "Pragmatic Play",
    maxWin: "3000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/running-sushi/",
  },
  {
    name: "Money Stack",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/money-stack/",
  },
  {
    name: "Sugar Rush Dice",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sugar-rush-dice/",
  },
  {
    name: "Jackpot Hunter",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/jackpot-hunter/",
  },
  {
    name: "Sumo Supreme Megaways",
    provider: "Pragmatic Play",
    maxWin: "12500x",
    demo: "https://clashofslots.com/slots/pragmatic-play//sumo-supreme-megaways",
  },
  {
    name: "Dynamite Diggin Doug",
    provider: "Pragmatic Play",
    maxWin: "3000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/dynamite-diggin-doug/",
  },
  {
    name: "Bow of Artemis",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/bow-of-artemis/",
  },
  {
    name: "Samurai Code",
    provider: "Pragmatic Play",
    maxWin: "4000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/samurai-code/",
  },
  {
    name: "Crank it Up",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/crank-it-up/",
  },
  {
    name: "Sweet Kingdom",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sweet-kingdom/",
  },
  {
    name: "Hand of Midas 2",
    provider: "Pragmatic Play",
    maxWin: "8000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/hand-of-midas-2/",
  },
  {
    name: "Buffalo King Untamed Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/buffalo-king-untamed-megaways/",
  },
  {
    name: "Big Bass Mission Fishin'",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-mission-fishin/",
  },
  {
    name: "Medusa's Stone",
    provider: "Pragmatic Play",
    maxWin: "7000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/medusas-stone/",
  },
  {
    name: "Devilicious",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/devilicious/",
  },
  {
    name: "Wildies",
    provider: "Pragmatic Play",
    maxWin: "7500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wildies/",
  },
  {
    name: "Big Bass Bonanza - Reel Action",
    provider: "Pragmatic Play",
    maxWin: "2100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-bonanza-reel-action/",
  },
  {
    name: "Sweet Bonanza 1000",
    provider: "Pragmatic Play",
    maxWin: "25000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sweet-bonanza-1000/",
  },
  {
    name: "Starlight Princess Pachi",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/starlight-princess-pachi/",
  },
  {
    name: "Rise of Pyramids",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/rise-of-pyramids/",
  },
  {
    name: "Revenge of Loki Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/revenge-of-loki-megaways/",
  },
  {
    name: "Dwarf & Dragon",
    provider: "Pragmatic Play",
    maxWin: "14000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/dwarf-dragon/",
  },
  {
    name: "Odds On Winner",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/odds-on-winner/",
  },
  {
    name: "Heroic Spins",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/heroic-spins/",
  },
  {
    name: "Heart of Cleopatra",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/heart-of-cleopatra/",
  },
  {
    name: "Fruity Treats",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fruity-treats/",
  },
  {
    name: "Candy Blitz Bombs",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/candy-blitz-bombs/",
  },
  {
    name: "Lobster Bob's Sea Food and Win It",
    provider: "Pragmatic Play",
    maxWin: "3000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/lobster-bobs-sea-food-and-win-it/",
  },
  {
    name: "Barnyard Megahays Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/barnyard-megahays-megaways/",
  },
  {
    name: "Ice Lobster",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/ice-lobster/",
  },
  {
    name: "Release the Bison",
    provider: "Pragmatic Play",
    maxWin: "3000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/release-the-bison/",
  },
  {
    name: "Big Bass Secrets of the Golden Lake",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-secrets-of-the-golden-lake/",
  },
  {
    name: "Aztec Powernudge",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/aztec-powernudge/",
  },
  {
    name: "Ripe Rewards",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/ripe-rewards/",
  },
  {
    name: "The Dog House - Dog or Alive",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-dog-house-dog-or-alive/",
  },
  {
    name: "Big Burger Load It up with Xtra Cheese",
    provider: "Pragmatic Play",
    maxWin: "3000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-burger-load-it-up-with-xtra-cheese/",
  },
  {
    name: "Fire Portals",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fire-portals/",
  },
  {
    name: "Pot of Fortune",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/pot-of-fortune/",
  },
  {
    name: "Beware The Deep Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/beware-the-deep-megaways/",
  },
  {
    name: "Big Bass Day at the Races",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-day-at-the-races/",
  },
  {
    name: "Gears of Horus",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gears-of-horus/",
  },
  {
    name: "Sugar Rush 1000",
    provider: "Pragmatic Play",
    maxWin: "25000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sugar-rush-1000/",
  },
  {
    name: "Gates of Olympus Dice",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gates-of-olympus-dice/",
  },
  {
    name: "Strawberry Cocktail",
    provider: "Pragmatic Play",
    maxWin: "16000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/strawberry-cocktail/",
  },
  {
    name: "Mighty Munching Melons",
    provider: "Pragmatic Play",
    maxWin: "3000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mighty-munching-melons/",
  },
  {
    name: "Pompeii Megareels Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/pompeii-megareels-megaways/",
  },
  {
    name: "Wheel O'Gold",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wheel-ogold/",
  },
  {
    name: "Big Bass Floats My Boat",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-floats-my-boat/",
  },
  {
    name: "Red Hot Luck",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/red-hot-luck/",
  },
  {
    name: "Trees of Treasure",
    provider: "Pragmatic Play",
    maxWin: "15000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/trees-of-treasure/",
  },
  {
    name: "The Alter Ego",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-alter-ego/",
  },
  {
    name: "Loki's Riches",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/lokis-riches/",
  },
  {
    name: "Blazing wilds Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/blazing-wilds-megaways/",
  },
  {
    name: "Castle of Fire",
    provider: "Pragmatic Play",
    maxWin: "8000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/castle-of-fire/",
  },
  {
    name: "Good Luck & Good Fortune",
    provider: "Pragmatic Play",
    maxWin: "2100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/good-luck-good-fortune/",
  },
  {
    name: "The Big Dawgs",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-big-dawgs/",
  },
  {
    name: "Blade & Fangs",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/blades-fangs/",
  },
  {
    name: "Year Of The Dragon King",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/year-of-the-dragon-king/",
  },
  {
    name: "Gates of Olympus 1000",
    provider: "Pragmatic Play",
    maxWin: "15000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gates-of-olympus-1000/",
  },
  {
    name: "Juicy Fruits Multihold",
    provider: "Pragmatic Play",
    maxWin: "8000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/juicy-fruits-multihold/",
  },
  {
    name: "Fire Stampede",
    provider: "Pragmatic Play",
    maxWin: "4275x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fire-stampede/",
  },
  {
    name: "Floating Dragon New Year Festival Ultra Megaways Hold & Spin",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/floating-dragon-new-year-festival-ultra-megaways-hold-spin/",
  },
  {
    name: "Candy Jar Clusters",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/candy-jas-clusters/",
  },
  {
    name: "Ding Dong Christmas Bells",
    provider: "Pragmatic Play",
    maxWin: "2100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/ding-dong-christmas-bell/",
  },
  {
    name: "Sugar Rush Xmas",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sugar-rush-xmas/",
  },
  {
    name: "5 Frozen Charms Megaways",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/5-frozen-charms-megaways/",
  },
  {
    name: "Big Bass Christmas Bash",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-christams-bash/",
  },
  {
    name: "Nile Fortune",
    provider: "Pragmatic Play",
    maxWin: "2500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/nile-fortune/",
  },
  {
    name: "Chase For Glory",
    provider: "Pragmatic Play",
    maxWin: "7887x",
    demo: "https://clashofslots.com/slots/pragmatic-play/chase-for-glory/",
  },
  {
    name: "Timber Stacks",
    provider: "Pragmatic Play",
    maxWin: "8000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/timber-stacks/",
  },
  {
    name: "The Wild Gang",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-wild-gang/",
  },
  {
    name: "Sugar Supreme Powernudge",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sugar-supreme-powernudge/",
  },
  {
    name: "Viking Forge",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/viking-forge/",
  },
  {
    name: "The Money Men Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-money-men-megaways/",
  },
  {
    name: "Big Bass Halloween",
    provider: "Pragmatic Play",
    maxWin: "2100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-halloween/",
  },
  {
    name: "Tundra's Fortune",
    provider: "Pragmatic Play",
    maxWin: "12500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/tundras-fortune/",
  },
  {
    name: "Cash Chips",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/cash-chips/",
  },
  {
    name: "Demon Pots",
    provider: "Pragmatic Play",
    maxWin: "6000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/demon-pots/",
  },
  {
    name: "Infective Wild",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/infective-wild/",
  },
  {
    name: "Twilight Princess",
    provider: "Pragmatic Play",
    maxWin: "7500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/twilight-princess/",
  },
  {
    name: "Gravity Bonanza",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gravity-bonanza/",
  },
  {
    name: "Rainbow Reels",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/rainbow-reels/",
  },
  {
    name: "8 Golden Dragon Challenge",
    provider: "Pragmatic Play",
    maxWin: "8800x",
    demo: "https://clashofslots.com/slots/pragmatic-play/8-golden-dragon-challenge/",
  },
  {
    name: "Fortunes of Aztec",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fortunes-of-aztec/",
  },
  {
    name: "Gold Oasis",
    provider: "Pragmatic Play",
    maxWin: "7260x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gold-oasis/",
  },
  {
    name: "Book of Tut Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/book-of-tut-megaways/",
  },
  {
    name: "Cyclops Smash",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/cyclops-smash/",
  },
  {
    name: "Candy Blitz",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/candy-blitz/",
  },
  {
    name: "Big Bass Hold & Spinner Megaways",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-hold-spinner-megaways/",
  },
  {
    name: "Frozen Tropics",
    provider: "Pragmatic Play",
    maxWin: "9000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/frozen-topics/",
  },
  {
    name: "Forge of Olympus",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/forge-of-olympus/",
  },
  {
    name: "Mustang Trail",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mustang-trail/",
  },
  {
    name: "Pub Kings",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/pub-kings/",
  },
  {
    name: "Piggy Bankers",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/piggy-bankers/",
  },
  {
    name: "Rocket Blast Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/rocket-blast-megaways/",
  },
  {
    name: "Starlight Princess 1000",
    provider: "Pragmatic Play",
    maxWin: "15000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/starlight-princess-1000/",
  },
  {
    name: "Diamond Cascade",
    provider: "Pragmatic Play",
    maxWin: "8000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/diamond-cascade/",
  },
  {
    name: "Lobster Bob's Crazy Crab Shack",
    provider: "Pragmatic Play",
    maxWin: "6000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/lobster-bobs-crazy-crab-shack/",
  },
  {
    name: "Sky Bounty",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sky-bounty/",
  },
  {
    name: "3 Buzzing Wilds",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/3-buzzing-wilds/",
  },
  {
    name: "Cash Box",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/cash-box/",
  },
  {
    name: "Power of Merlin Megaways",
    provider: "Pragmatic Play",
    maxWin: "40000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/power-of-merlin-megaways/",
  },
  {
    name: "Hellvis Wild",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/hellvis-wild/",
  },
  {
    name: "Spellbinding Mystery",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/spellbinding-mystery/",
  },
  {
    name: "Wisdom of Athena",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wisdom-of-athena/",
  },
  {
    name: "Heist for the Golden Nuggets",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/heist-for-the-golden-nuggets/",
  },
  {
    name: "Big Bass Amazon Xtreme",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-amazon-xtreme/",
  },
  {
    name: "Fat Panda",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fat-banda/",
  },
  {
    name: "Country Farming",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/country-farming/",
  },
  {
    name: "Floating Dragon - Dragon Boat Festival",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/floating-dragon-dragon-boat-festival/",
  },
  {
    name: "Pirate's Pub",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/pirates-pub/",
  },
  {
    name: "Sticky Bees",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sticky-bees/",
  },
  {
    name: "Jewel Rush",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/jewel-rush/",
  },
  {
    name: "Lamp Of Infinity",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/lamp-of-infinity/",
  },
  {
    name: "Zeus vs Hades: Gods of War",
    provider: "Pragmatic Play",
    maxWin: "15000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/zeus-vs-hades-gods-of-war/",
  },
  {
    name: "Diamonds of Egypt",
    provider: "Pragmatic Play",
    maxWin: "2500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/diamonds-of-egypt/",
  },
  {
    name: "Knight Hot Spotz",
    provider: "Pragmatic Play",
    maxWin: "2000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/knight-hot-spotz/",
  },
  {
    name: "Wild Bison Charge",
    provider: "Pragmatic Play",
    maxWin: "12000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-bison-charge/",
  },
  {
    name: "Excalibur Unleashed",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/excalibur-unleashed/",
  },
  {
    name: "Kingdom of the Dead",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/kingdom-of-the-dead/",
  },
  {
    name: "Jane Hunter and the Mask of Montezuma",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/jane-hunter-and-the-mask-of-montezuma/",
  },
  {
    name: "3 Dancing Monkeys",
    provider: "Pragmatic Play",
    maxWin: "12077x",
    demo: "https://clashofslots.com/slots/pragmatic-play/3-dancing-monkeys/",
  },
  {
    name: "Wild Celebrity Bus Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-celebrity-bus-megaways/",
  },
  {
    name: "African Elephant",
    provider: "Pragmatic Play",
    maxWin: "15000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/african-elephant/",
  },
  {
    name: "Gods of Giza",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gods-of-giza/",
  },
  {
    name: "The Red Queen",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-red-queen/",
  },
  {
    name: "Big Bass - Hold & Spinner",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-hold-spinner/",
  },
  {
    name: "Rabbit Garden",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/rabbit-garden/",
  },
  {
    name: "The Knight King",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-knight-king/",
  },
  {
    name: "Jasmine Dreams",
    provider: "Pragmatic Play",
    maxWin: "2500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/jasmine-dreams/",
  },
  {
    name: "Mochimon",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mochimon/",
  },
  {
    name: "The Dog House Multihold",
    provider: "Pragmatic Play",
    maxWin: "9000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-dog-house-multihold/",
  },
  {
    name: "Wild West Duels",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-west-duels/",
  },
  {
    name: "Mystery of the Orient",
    provider: "Pragmatic Play",
    maxWin: "8035x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mystery-of-the-orient/",
  },
  {
    name: "Cowboy Coins",
    provider: "Pragmatic Play",
    maxWin: "30000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/cowboy-coins/",
  },
  {
    name: "Wild Wild Riches Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-wild-riches-megaways/",
  },
  {
    name: "Peak Power",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/peak-power/",
  },
  {
    name: "Club Tropicana",
    provider: "Pragmatic Play",
    maxWin: "4000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/club-tropicana/",
  },
  {
    name: "Sweet Bonanza Dice",
    provider: "Pragmatic Play",
    maxWin: "21100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sweet-bonanza-dice/",
  },
  {
    name: "Fire Archer",
    provider: "Pragmatic Play",
    maxWin: "4000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fire-archer/",
  },
  {
    name: "Monster Superlanche",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/monster-superlanche/",
  },
  {
    name: "The Dog House Dice Show",
    provider: "Pragmatic Play",
    maxWin: "6750x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-dog-house-dice-show/",
  },
  {
    name: "Fish Eye",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fish-eye/",
  },
  {
    name: "Mammoth Gold Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mammoth-gold-megaways/",
  },
  {
    name: "Secret City Gold",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/secret-city-gold/",
  },
  {
    name: "Pinup Girls",
    provider: "Pragmatic Play",
    maxWin: "3000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/pinup-girls/",
  },
  {
    name: "Wild Wild Bananas",
    provider: "Pragmatic Play",
    maxWin: "12000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-wild-bananas/",
  },
  {
    name: "Dragon Hero",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/dragon-hero/",
  },
  {
    name: "Sweet Powernudge",
    provider: "Pragmatic Play",
    maxWin: "4000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sweet-powernudge/",
  },
  {
    name: "PIZZA! PIZZA? PIZZA!",
    provider: "Pragmatic Play",
    maxWin: "7200x",
    demo: "https://clashofslots.com/slots/pragmatic-play/pizza-pizza-pizza/",
  },
  {
    name: "Hot Pepper",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/hot-pepper/",
  },
  {
    name: "Starlight Christmas",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/starlight-christmas/",
  },
  {
    name: "Reel Banks",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/reel-banks/",
  },
  {
    name: "Fury of Odin Megaways",
    provider: "Pragmatic Play",
    maxWin: "15000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fury-of-odin-megaways/",
  },
  {
    name: "Bigger Bass Blizzard - Christmas Catch",
    provider: "Pragmatic Play",
    maxWin: "4000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/bigger-bass-blizzard-christmas-catch/",
  },
  {
    name: "Snakes & Ladders - Snake Eyes",
    provider: "Pragmatic Play",
    maxWin: "5300x",
    demo: "https://clashofslots.com/slots/pragmatic-play/snakes-ladders-snake-eyes/",
  },
  {
    name: "Gems of Serengeti",
    provider: "Pragmatic Play",
    maxWin: "4000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gems-of-serengeti/",
  },
  {
    name: "Sheild Of Sparta",
    provider: "Pragmatic Play",
    maxWin: "3000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sheild-of-sparta/",
  },
  {
    name: "Santa's Great Gifts",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/santas-great-gifts/",
  },
  {
    name: "Towering Fortunes",
    provider: "Pragmatic Play",
    maxWin: "6422x",
    demo: "https://clashofslots.com/slots/pragmatic-play/towering-fortunes/",
  },
  {
    name: "Spin & Score Megaways",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/spin-score-megaways/",
  },
  {
    name: "Release the Kraken 2",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/release-the-kraken-2/",
  },
  {
    name: "Sword of Ares",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sword-of-ares/",
  },
  {
    name: "Big Bass Bonanza - Keeping It Reel",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-bonanza-keeping-it-reel/",
  },
  {
    name: "Muertos Multiplier Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/meurtos-multiplier-megaways/",
  },
  {
    name: "Firebird Spirit",
    provider: "Pragmatic Play",
    maxWin: "4250x",
    demo: "https://clashofslots.com/slots/pragmatic-play/firebird-spirit/",
  },
  {
    name: "Pirate Golden Age",
    provider: "Pragmatic Play",
    maxWin: "3000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/pirate-golden-age/",
  },
  {
    name: "Candy Stars",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/candy-stars/",
  },
  {
    name: "John Tut and the Book Of Tut Respin",
    provider: "Pragmatic Play",
    maxWin: "4000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/john-tut-and-the-book-of-tut-respin/",
  },
  {
    name: "Aztec Blaze",
    provider: "Pragmatic Play",
    maxWin: "2000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/aztec-blaze/",
  },
  {
    name: "Floating Dragon Hold & Spin Megaways",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/floating-dragon-hold-spin-megaways/",
  },
  {
    name: "Crown Of Fire",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/crown-of-fire/",
  },
  {
    name: "Book of Golden Sands",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/book-of-golden-sands/",
  },
  {
    name: "Wild Hop & Drop",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-hop-drop/",
  },
  {
    name: "Happy Hooves",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/happy-hooves/",
  },
  {
    name: "Octobeer Fortunes",
    provider: "Pragmatic Play",
    maxWin: "4500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/octobeer-fortunes/",
  },
  {
    name: "Fire Hot 100",
    provider: "Pragmatic Play",
    maxWin: "2700x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fire-hot-100/",
  },
  {
    name: "Down the Rails",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/down-the-rails/",
  },
  {
    name: "Hot To Burn Extreme",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/hot-to-burn-extreme/",
  },
  {
    name: "Black Bull",
    provider: "Pragmatic Play",
    maxWin: "4500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/black-bull/",
  },
  {
    name: "Greedy Wolf",
    provider: "Pragmatic Play",
    maxWin: "3000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/greedy-wolf/",
  },
  {
    name: "Magic Money Maze",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/magic-money-maze/",
  },
  {
    name: "Tropical Tiki",
    provider: "Pragmatic Play",
    maxWin: "3000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/tropical-tiki/",
  },
  {
    name: "Cosmic Cash",
    provider: "Pragmatic Play",
    maxWin: "2650x",
    demo: "https://clashofslots.com/slots/pragmatic-play/cosmic-cash/",
  },
  {
    name: "Gorilla Mayhem",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gorilla-mayhem/",
  },
  {
    name: "Bomb Bonanza",
    provider: "Pragmatic Play",
    maxWin: "2000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/bomb-bonanza/",
  },
  {
    name: "Sugar Rush",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sugar-rush/",
  },
  {
    name: "Big Bass Splash",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-splash/",
  },
  {
    name: "Cash Patrol",
    provider: "Pragmatic Play",
    maxWin: "10500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/cash-patrol/",
  },
  {
    name: "Queen of Gods",
    provider: "Pragmatic Play",
    maxWin: "1839x",
    demo: "https://clashofslots.com/slots/pragmatic-play/queen-of-gods/",
  },
  {
    name: "Fortune of Giza",
    provider: "Pragmatic Play",
    maxWin: "6750x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fortune-of-giza/",
  },
  {
    name: "Zombie Carinval",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/zombie-carnival/",
  },
  {
    name: "Wild West Gold Megaways",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-west-gold-megaways/",
  },
  {
    name: "Cleocatra",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/cleocatra/",
  },
  {
    name: "The Great Stick-Up",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-grat-stick-up/",
  },
  {
    name: "Goblin Heist Powernudge",
    provider: "Pragmatic Play",
    maxWin: "4000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/goblin-heist-powernudge/",
  },
  {
    name: "Fire Strike 2",
    provider: "Pragmatic Play",
    maxWin: "25000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fire-strike-2/",
  },
  {
    name: "North Guardians",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/north-guardians/",
  },
  {
    name: "Spirit of Adventure",
    provider: "Pragmatic Play",
    maxWin: "5100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/spirit-of-adventure/",
  },
  {
    name: "Clover Gold",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/clover-gold/",
  },
  {
    name: "Eye of Cleopatra",
    provider: "Pragmatic Play",
    maxWin: "3200x",
    demo: "https://clashofslots.com/slots/pragmatic-play/eye-of-cleopatra/",
  },
  {
    name: "Chicken Chase",
    provider: "Pragmatic Play",
    maxWin: "210x",
    demo: "https://clashofslots.com/slots/pragmatic-play/chicken-chase/",
  },
  {
    name: "Drill That Gold",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/drill-that-gold/",
  },
  {
    name: "Barn Festival",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/barn-festival/",
  },
  {
    name: "Tic Tac Take",
    provider: "Pragmatic Play",
    maxWin: "2200x",
    demo: "https://clashofslots.com/slots/pragmatic-play/tic-tac-take/",
  },
  {
    name: "Rainbow Gold",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/rainbow-gold/",
  },
  {
    name: "Queenie",
    provider: "Pragmatic Play",
    maxWin: "4200x",
    demo: "https://clashofslots.com/slots/pragmatic-play/queenie/",
  },
  {
    name: "Wild Beach Party",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-beach-party/",
  },
  {
    name: "Extra Juicy Megaways",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/extra-juicy-megaways/",
  },
  {
    name: "Snakes & Ladders Megadice",
    provider: "Pragmatic Play",
    maxWin: "5300x",
    demo: "https://clashofslots.com/slots/pragmatic-play/snakes-ladders-megadice/",
  },
  {
    name: "Might of Ra",
    provider: "Pragmatic Play",
    maxWin: "22500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/might-of-ra/",
  },
  {
    name: "Elemental Gems Megaways",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/elemental-gems-megaways/",
  },
  {
    name: "The Ultimate 5",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-ultimate-5/",
  },
  {
    name: "Colossal Cash Zone",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/colossal-cash-zone/",
  },
  {
    name: "Gates of Valhalla",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gates-of-valhalla/",
  },
  {
    name: "Rock Vegas",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play//",
  },
  {
    name: "Gold Party",
    provider: "Pragmatic Play",
    maxWin: "5163x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gold-party/",
  },
  {
    name: "Crystal Caverns Megaways",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/crystal-caverns-megaways/",
  },
  {
    name: "Dragon Kingdom",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/dragon-kingdom/",
  },
  {
    name: "Heart of Rio",
    provider: "Pragmatic Play",
    maxWin: "10500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/heart-of-rio/",
  },
  {
    name: "Jungle Gorilla",
    provider: "Pragmatic Play",
    maxWin: "2800x",
    demo: "https://clashofslots.com/slots/pragmatic-play/jungle-gorilla/",
  },
  {
    name: "Lucky Lightning",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/lucky-lightning/",
  },
  {
    name: "Mustang Gold",
    provider: "Pragmatic Play",
    maxWin: "12000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mustang-gold/",
  },
  {
    name: "Piggy Bank Bills",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/piggy-bank-bills/",
  },
  {
    name: "Romeo and Juliet",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/romeo-and-juliet/",
  },
  {
    name: "Starlight Princess",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/starlight-princess/",
  },
  {
    name: "Sweet Bonanza Xmas",
    provider: "Pragmatic Play",
    maxWin: "21100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sweet-bonanza-xmas/",
  },
  {
    name: "7 Monkeys",
    provider: "Pragmatic Play",
    maxWin: "7500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/7-monkeys/",
  },
  {
    name: "Big Bass Bonanza Megaways",
    provider: "Pragmatic Play",
    maxWin: "4000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-bonanza-megaways/",
  },
  {
    name: "Da Vinci's Treasure",
    provider: "Pragmatic Play",
    maxWin: "48000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/davincis-treasure/",
  },
  {
    name: "Hercules Son of Zeus",
    provider: "Pragmatic Play",
    maxWin: "40000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/hercules-son-of-zeus/",
  },
  {
    name: "Hokey League Wild Match",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play//",
  },
  {
    name: "Journey to the West",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/journey-to-the-west/",
  },
  {
    name: "Lady Godiva",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/lady-godiva/",
  },
  {
    name: "Leprechaun Song",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/leprechaun-song/",
  },
  {
    name: "Magician's Secrets",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/magicians-secrets/",
  },
  {
    name: "Mystic Chief",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mystic-chief/",
  },
  {
    name: "Panther Queen",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/panter-queen/",
  },
  {
    name: "Santa",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/santa/",
  },
  {
    name: "The Catfather",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-catfather/",
  },
  {
    name: "The Catfather 2",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-catfather-2/",
  },
  {
    name: "Vegas Nights",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/vegas-nights/",
  },
  {
    name: "Wild Gladiators",
    provider: "Pragmatic Play",
    maxWin: "100000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-gladiators/",
  },
  {
    name: "Buffalo King",
    provider: "Pragmatic Play",
    maxWin: "93750x",
    demo: "https://clashofslots.com/slots/pragmatic-play/buffalo-king/",
  },
  {
    name: "Chilli Heat",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/chilli-heat/",
  },
  {
    name: "Gold Rush",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gold-rush/",
  },
  {
    name: "Magic Crystals",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/magic-crystals/",
  },
  {
    name: "Power of Thor Megaways",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/power-of-thor-megaways/",
  },
  {
    name: "Pyramid King",
    provider: "Pragmatic Play",
    maxWin: "2500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/pyramid-king/",
  },
  {
    name: "Star Bounty",
    provider: "Pragmatic Play",
    maxWin: "25000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/star-bounty/",
  },
  {
    name: "Street Racer",
    provider: "Pragmatic Play",
    maxWin: "2000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/street-racer/",
  },
  {
    name: "Super X",
    provider: "Pragmatic Play",
    maxWin: "9000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/super-x/",
  },
  {
    name: "The Wild Machine",
    provider: "Pragmatic Play",
    maxWin: "7000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-wild-machine/",
  },
  {
    name: "Treasure Wild",
    provider: "Pragmatic Play",
    maxWin: "4500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/treasure-wild/",
  },
  {
    name: "Wild Pixies",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-pixies/",
  },
  {
    name: "Wild Walker",
    provider: "Pragmatic Play",
    maxWin: "4900x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-walker/",
  },
  {
    name: "5 Lions",
    provider: "Pragmatic Play",
    maxWin: "3520x",
    demo: "https://clashofslots.com/slots/pragmatic-play/5-lions/",
  },
  {
    name: "Big Juan",
    provider: "Pragmatic Play",
    maxWin: "2600x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-juan/",
  },
  {
    name: "Book of Kingdoms",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/book-of-kingdoms/",
  },
  {
    name: "Buffalo King Megaways",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/buffalo-king-megaways/",
  },
  {
    name: "Curse of the Werewolf Megaways",
    provider: "Pragmatic Play",
    maxWin: "40000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/curse-of-the-werewolf-megaways/",
  },
  {
    name: "Dragon Hot Hold & Spin",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/dragon-hot-hold-spin/",
  },
  {
    name: "Egyptian Fortunes",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/egyptian-fortunes/",
  },
  {
    name: "Fruit Rainbow",
    provider: "Pragmatic Play",
    maxWin: "2000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fruit-rainbow/",
  },
  {
    name: "Glorious Rome",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/glorious-rome/",
  },
  {
    name: "Great Rhino Megaways",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/great-rhino-megaways/",
  },
  {
    name: "Money Mouse",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/money-mouse/",
  },
  {
    name: "Pirate Gold",
    provider: "Pragmatic Play",
    maxWin: "32270x",
    demo: "https://clashofslots.com/slots/pragmatic-play/pirate-gold/",
  },
  {
    name: "Sweet Bonanza",
    provider: "Pragmatic Play",
    maxWin: "21100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/sweet-bonanza/",
  },
  {
    name: "The Hand of Midas",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-hand-of-midas/",
  },
  {
    name: "Triple Jokers",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/triple-jokers/",
  },
  {
    name: "Vegas Magic",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/vegas-magic/",
  },
  {
    name: "Wild Booster",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-booster/",
  },
  {
    name: "Wild Spells",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-spells/",
  },
  {
    name: "7 Piggies",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/7-piggies/",
  },
  {
    name: "John Hunter and the Book of Tut",
    provider: "Pragmatic Play",
    maxWin: "5500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/john-hunter-and-the-book-of-tut/",
  },
  {
    name: "Drago - Jewels of Fortune",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/drago-jewels-of-fortune/",
  },
  {
    name: "Dwarven Gold",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/dwarven-gold/",
  },
  {
    name: "Fishin Reels",
    provider: "Pragmatic Play",
    maxWin: "1200x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fishin-reels/",
  },
  {
    name: "Floating Dragon",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/floating-dragon/",
  },
  {
    name: "Gates of Olympus",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gates-of-olympus/",
  },
  {
    name: "Great Rhino",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/great-rhino/",
  },
  {
    name: "Greek Gods",
    provider: "Pragmatic Play",
    maxWin: "1000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/greek-gods/",
  },
  {
    name: "Hercules and Pegasus",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/hercules-and-pegasus/",
  },
  {
    name: "Honey Honey Honey",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/honey-honey-honey/",
  },
  {
    name: "John Hunter And The Mayan Gods",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/john-hunter-and-the-mayan-gods/",
  },
  {
    name: "John Hunter and the Tomb of the Scarab Queen",
    provider: "Pragmatic Play",
    maxWin: "10500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/john-hunter-and-the-tomb-of-the-scarab-queen/",
  },
  {
    name: "Leprechaun Carol",
    provider: "Pragmatic Play",
    maxWin: "6000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/leprechaun-carol/",
  },
  {
    name: "Lucky Dragons",
    provider: "Pragmatic Play",
    maxWin: "40000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/lucky-dragons/",
  },
  {
    name: "Lucky New Year",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/lucky-new-year/",
  },
  {
    name: "Mighty Kong",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mighty-kong/",
  },
  {
    name: "Pirate Gold Deluxe",
    provider: "Pragmatic Play",
    maxWin: "15000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/pirate-gold-deluxe/",
  },
  {
    name: "Rise of Giza Powernudge",
    provider: "Pragmatic Play",
    maxWin: "4000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/rise-of-giza-powernudge/",
  },
  {
    name: "Safari King",
    provider: "Pragmatic Play",
    maxWin: "1000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/safari-king/",
  },
  {
    name: "Santa's Wonderland",
    provider: "Pragmatic Play",
    maxWin: "7500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/santas-wonderland/",
  },
  {
    name: "Wild Depths",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-depths/",
  },
  {
    name: "5 Lions Dance",
    provider: "Pragmatic Play",
    maxWin: "2700x",
    demo: "https://clashofslots.com/slots/pragmatic-play/5-lions-dance/",
  },
  {
    name: "8 Dragons",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/8-dragons/",
  },
  {
    name: "Aladdin's Treasure",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/aladdins-treasure/",
  },
  {
    name: "Aztec Gems Deluxe",
    provider: "Pragmatic Play",
    maxWin: "22500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/aztec-gems-deluxe/",
  },
  {
    name: "John Hunter and the Aztec Treasure",
    provider: "Pragmatic Play",
    maxWin: "9000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/john-hunter-and-the-aztec-treasure/",
  },
  {
    name: "Book of Vikings",
    provider: "Pragmatic Play",
    maxWin: "5500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/book-of-vikings/",
  },
  {
    name: "Bounty Gold",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/bounty-gold/",
  },
  {
    name: "Caishen's Cash",
    provider: "Pragmatic Play",
    maxWin: "22500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/caishens-cash/",
  },
  {
    name: "Chilli Heat Megaways",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/chilli-heat-megaways/",
  },
  {
    name: "Christmas Carol Megaways",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/christmas-carol-megaways/",
  },
  {
    name: "Cowboys Gold",
    provider: "Pragmatic Play",
    maxWin: "6065x",
    demo: "https://clashofslots.com/slots/pragmatic-play/cowboys-gold/",
  },
  {
    name: "Emerald King",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/emerald-king/",
  },
  {
    name: "Emerald King Rainbow Road",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/emerald-king-rainbow-road/",
  },
  {
    name: "Empty the Bank",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/empty-the-bank/",
  },
  {
    name: "Hot To Burn",
    provider: "Pragmatic Play",
    maxWin: "1000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/hot-to-burn/",
  },
  {
    name: "Joker King",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/joker-king/",
  },
  {
    name: "Monkey Warrior",
    provider: "Pragmatic Play",
    maxWin: "6000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/monkey-warrior/",
  },
  {
    name: "Panda's Fortune",
    provider: "Pragmatic Play",
    maxWin: "8000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/pandas-fortune/",
  },
  {
    name: "Smugglers Cove",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/smugglers-cove/",
  },
  {
    name: "Spartan King",
    provider: "Pragmatic Play",
    maxWin: "7480x",
    demo: "https://clashofslots.com/slots/pragmatic-play/spartan-king/",
  },
  {
    name: "The Dog House Megaways",
    provider: "Pragmatic Play",
    maxWin: "12000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-dog-house-megaways/",
  },
  {
    name: "Wild West Gold",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-west-gold/",
  },
  {
    name: "5 Lions Gold",
    provider: "Pragmatic Play",
    maxWin: "7000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/5-lions-gold/",
  },
  {
    name: "5 Lions Megaways",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/5-lions-megaways/",
  },
  {
    name: "Asgard",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/asgard/",
  },
  {
    name: "Caishen's Gold",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/caishens-gold/",
  },
  {
    name: "Cash Elevator",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/cash-elevator/",
  },
  {
    name: "Dance Party",
    provider: "Pragmatic Play",
    maxWin: "36450x",
    demo: "https://clashofslots.com/slots/pragmatic-play/dance-party/",
  },
  {
    name: "Fairytale Fortune",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fairytale-fortune/",
  },
  {
    name: "Gems Bonanza",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gems-bonanza/",
  },
  {
    name: "Great Rhino Deluxe",
    provider: "Pragmatic Play",
    maxWin: "6000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/great-rhino-deluxe/",
  },
  {
    name: "Hot Safari",
    provider: "Pragmatic Play",
    maxWin: "100000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/hot-safari/",
  },
  {
    name: "Hot to Burn Hold and Spin",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/hot-to-burn-hold-and-spin/",
  },
  {
    name: "Jurassic Giants",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/jurassic-giants/",
  },
  {
    name: "Lucky, Grace & Charm",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/lucky-grace-charm/",
  },
  {
    name: "Release the Kraken",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/release-the-kraken/",
  },
  {
    name: "The Dragon Tiger",
    provider: "Pragmatic Play",
    maxWin: "18000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-dragon-tiger/",
  },
  {
    name: "Wild Wild Riches",
    provider: "Pragmatic Play",
    maxWin: "4600x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wild-wild-riches/",
  },
  {
    name: "Yum Yum Powerways",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/yum-yum-powerways/",
  },
  {
    name: "Aztec Bonanza",
    provider: "Pragmatic Play",
    maxWin: "19000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/aztec-bonanza/",
  },
  {
    name: "Cash Bonanza",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/cash-bonanza/",
  },
  {
    name: "Chicken Drop",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/chicken-drop/",
  },
  {
    name: "Congo Cash",
    provider: "Pragmatic Play",
    maxWin: "2200x",
    demo: "https://clashofslots.com/slots/pragmatic-play/congo-cash/",
  },
  {
    name: "Dwarven Gold Deluxe",
    provider: "Pragmatic Play",
    maxWin: "2000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/dwarven-gold-deluxe/",
  },
  {
    name: "Fruit Party",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fruit-party/",
  },
  {
    name: "Fruit Party 2",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/fruit-party-2/",
  },
  {
    name: "Gold Train",
    provider: "Pragmatic Play",
    maxWin: "1000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/gold-train/",
  },
  {
    name: "Hot Fiesta",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/hot-fiesta/",
  },
  {
    name: "Juicy Fruits",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/juicy-fruits/",
  },
  {
    name: "Madame Destiny Megaways",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/madame-destiny-megaways/",
  },
  {
    name: "Master Chen's Fortune",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/master-chens-fortune/",
  },
  {
    name: "Mysterious",
    provider: "Pragmatic Play",
    maxWin: "7500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mysterious/",
  },
  {
    name: "Mysterious Egypt",
    provider: "Pragmatic Play",
    maxWin: "5500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/mysterious-egypt/",
  },
  {
    name: "Panda Fortune 2",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/panda-frotune-2/",
  },
  {
    name: "Peking Luck",
    provider: "Pragmatic Play",
    maxWin: "180000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/peking-luck/",
  },
  {
    name: "Phoenix Forge",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/phoenix-forge/",
  },
  {
    name: "Pixie Wings",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/pixie-wings/",
  },
  {
    name: "Star Pirates Code",
    provider: "Pragmatic Play",
    maxWin: "2500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/star-pirates-code/",
  },
  {
    name: "Tales of Egypt",
    provider: "Pragmatic Play",
    maxWin: "1000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/tales-of-egypt/",
  },
  {
    name: "The Magic Cauldron",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-magic-cauldron/",
  },
  {
    name: "Voodoo Magic",
    provider: "Pragmatic Play",
    maxWin: "1000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/voodo-magic/",
  },
  {
    name: "Wolf Gold",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/wolf-gold/",
  },
  {
    name: "Aladdin and the Sorcerer",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/aladdin-and-the-sorcerer/",
  },
  {
    name: "Amazing Money Machine",
    provider: "Pragmatic Play",
    maxWin: "5100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/amazing-money-machine/",
  },
  {
    name: "Ancient Egypt Classic",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/ancient-egypt-classic/",
  },
  {
    name: "Big Bass Bonanza",
    provider: "Pragmatic Play",
    maxWin: "2100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/big-bass-bonanza/",
  },
  {
    name: "Day of Dead",
    provider: "Pragmatic Play",
    maxWin: "4500x",
    demo: "https://clashofslots.com/slots/pragmatic-play/day-of-dead/",
  },
  {
    name: "Lady of the Moon",
    provider: "Pragmatic Play",
    maxWin: "3300x",
    demo: "https://clashofslots.com/slots/pragmatic-play/lady-of-the-moon/",
  },
  {
    name: "Return of the Dead",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/return-of-the-dead/",
  },
  {
    name: "Vampires vs Wolves",
    provider: "Pragmatic Play",
    maxWin: "1000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/vampires-vs-wolves/",
  },
  {
    name: "John Hunter and the Quest for Bermuda Riches",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/john-hunter-and-the-quest-for-bermuda-riches/",
  },
  {
    name: "Extra Juicy",
    provider: "Pragmatic Play",
    maxWin: "60000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/extra-juicy/",
  },
  {
    name: "Eye of the Storm",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/eye-of-the-storm/",
  },
  {
    name: "Jade Butterfly",
    provider: "Pragmatic Play",
    maxWin: "10000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/jade-butterfly/",
  },
  {
    name: "Madame Destiny",
    provider: "Pragmatic Play",
    maxWin: "900x",
    demo: "https://clashofslots.com/slots/pragmatic-play/madame-destiny/",
  },
  {
    name: "Queen of Atlantis",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/queen-of-atlantis/",
  },
  {
    name: "Treasure Horse",
    provider: "Pragmatic Play",
    maxWin: "6000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/treasure-horse/",
  },
  {
    name: "Book of the Fallen",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/book-of-the-fallen/",
  },
  {
    name: "Temujin Treasures",
    provider: "Pragmatic Play",
    maxWin: "9000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/temujin-treasures/",
  },
  {
    name: "The Dog House",
    provider: "Pragmatic Play",
    maxWin: "6750x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-dog-house/",
  },
  {
    name: "The Great Chicken Escape",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/the-great-chicken-escape/",
  },
  {
    name: "Three Star Fortune",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/three-star-fortune/",
  },
  {
    name: "Ancient Egypt",
    provider: "Pragmatic Play",
    maxWin: "5000x",
    demo: "https://clashofslots.com/slots/pragmatic-play//",
  },
  {
    name: "Bigger Bass Bonanza",
    provider: "Pragmatic Play",
    maxWin: "4000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/bigger-bass-bonanza/",
  },
  {
    name: "Christmas Big Bass Bonanza",
    provider: "Pragmatic Play",
    maxWin: "2100x",
    demo: "https://clashofslots.com/slots/pragmatic-play/christmas-big-bass-bonanza/",
  },
  {
    name: "3 Genie Wishes",
    provider: "Pragmatic Play",
    maxWin: "20000x",
    demo: "https://clashofslots.com/slots/pragmatic-play/3-genie-wishes/",
  },
);
